import { Inter } from "next/font/google";
import { Metadata } from "next";

import "bootstrap/dist/css/bootstrap.min.css";
/* Custom Styles  */
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>{children}</body>
		</html>
	);
}
